import greenfoot.*;  // (World, Actor, GreenfootImage, Greenfoot and MouseInfo)

/**
 * Write a description of class MyWorld here.
 * 
 * @author (your name) 
 * @version (a version number or a date)
 */
public class MyWorld extends World
{

    /**
     * Constructor for objects of class MyWorld.
     * 
     */
    public MyWorld()
    {    
        // Create a new world with 600x400 cells with a cell size of 1x1 pixels.
        super(750, 600, 1); 
        prepare();
    }
    
    /**
     * Prepare the world for the start of the program.
     * That is: create the initial objects and add them to the world.
     */
    private void prepare()
    {
        Enemy enemy = new Enemy();
        addObject(enemy, Greenfoot.getRandomNumber(750), Greenfoot.getRandomNumber(550));
        Enemy enemy2 = new Enemy();
        addObject(enemy2, Greenfoot.getRandomNumber(750), Greenfoot.getRandomNumber(550));
        Enemy enemy3 = new Enemy();
        addObject(enemy3, Greenfoot.getRandomNumber(750), Greenfoot.getRandomNumber(550));
        WallWidthLong wallWidthLong = new WallWidthLong();
        addObject(wallWidthLong,202,2);
        wallWidthLong.setLocation(222,-3);
        WallWidthLong wallWidthLong2 = new WallWidthLong();
        addObject(wallWidthLong2,491,7);
        wallWidthLong2.setLocation(597,-2);
        wallWidthLong2.setLocation(574,5);
        wallWidthLong2.setLocation(580,-3);
        wallWidthLong2.setLocation(562,3);
        wallWidthLong2.setLocation(562,2);
        WallWidthLong wallWidthLong3 = new WallWidthLong();
        addObject(wallWidthLong3,97,588);
        wallWidthLong3.setLocation(266,589);
        wallWidthLong3.setLocation(217,594);
        WallWidthLong wallWidthLong4 = new WallWidthLong();
        addObject(wallWidthLong4,501,583);
        wallWidthLong4.setLocation(556,587);
        wallWidthLong4.setLocation(558,594);
        WallHeightSmall wallHeightSmall = new WallHeightSmall();
        addObject(wallHeightSmall,515,192);
        wallHeightSmall.setLocation(448,148);
        wallHeightSmall.setLocation(449,151);
        WallHeightSmall wallHeightSmall2 = new WallHeightSmall();
        addObject(wallHeightSmall2,276,79);
        wallHeightSmall2.setLocation(299,92);
        WallHeightSmall wallHeightSmall3 = new WallHeightSmall();
        addObject(wallHeightSmall3,297,197);
        wallHeightSmall3.setLocation(298,216);
        wallHeightSmall3.setLocation(300,211);
        WallHeightSmall wallHeightSmall4 = new WallHeightSmall();
        addObject(wallHeightSmall4,293,543);
        wallHeightSmall4.setLocation(299,565);
        WallHeightSmall wallHeightSmall5 = new WallHeightSmall();
        addObject(wallHeightSmall5,151,564);
        wallHeightSmall5.setLocation(150,565);
        WallHeightSmall wallHeightSmall6 = new WallHeightSmall();
        addObject(wallHeightSmall6,58,512);
        wallHeightSmall6.setLocation(71,505);
        wallHeightSmall6.setLocation(75,508);
        WallHeightSmall wallHeightSmall7 = new WallHeightSmall();
        addObject(wallHeightSmall7,298,381);
        wallHeightSmall7.setLocation(300,389);
        WallHeightSmall wallHeightSmall8 = new WallHeightSmall();
        addObject(wallHeightSmall8,216,260);
        wallHeightSmall8.setLocation(225,269);
        WallHeightSmall wallHeightSmall9 = new WallHeightSmall();
        addObject(wallHeightSmall9,371,269);
        wallHeightSmall9.setLocation(374,269);
        WallHeightSmall wallHeightSmall10 = new WallHeightSmall();
        addObject(wallHeightSmall10,159,120);
        wallHeightSmall10.setLocation(148,90);
        WallHeightSmall wallHeightSmall11 = new WallHeightSmall();
        addObject(wallHeightSmall11,72,314);
        wallHeightSmall11.setLocation(74,328);
        WallWidthSmall wallWidthSmall = new WallWidthSmall();
        addObject(wallWidthSmall,628,241);
        wallWidthSmall.setLocation(633,241);
        WallWidthSmall wallWidthSmall2 = new WallWidthSmall();
        addObject(wallWidthSmall2,397,245);
        wallWidthSmall2.setLocation(410,238);
        WallWidthSmall wallWidthSmall3 = new WallWidthSmall();
        addObject(wallWidthSmall3,638,481);
        wallWidthSmall3.setLocation(637,477);
        WallWidthSmall wallWidthSmall4 = new WallWidthSmall();
        addObject(wallWidthSmall4,470,421);
        wallWidthSmall4.setLocation(486,421);
        WallWidthSmall wallWidthSmall5 = new WallWidthSmall();
        addObject(wallWidthSmall5,108,52);
        wallWidthSmall5.setLocation(107,63);
        WallWidthSmall wallWidthSmall6 = new WallWidthSmall();
        addObject(wallWidthSmall6,250,418);
        wallWidthSmall6.setLocation(261,419);
        WallWidthSmall wallWidthSmall7 = new WallWidthSmall();
        addObject(wallWidthSmall7,169,539);
        wallWidthSmall7.setLocation(183,539);
        wallWidthSmall7.setLocation(190,539);
        WallWidthSmall wallWidthSmall8 = new WallWidthSmall();
        addObject(wallWidthSmall8,29,298);
        wallWidthSmall8.setLocation(33,299);
        WallWidthMedium wallWidthMedium = new WallWidthMedium();
        addObject(wallWidthMedium,201,299);
        wallWidthMedium.setLocation(222,299);
        WallWidthSmall wallWidthSmall9 = new WallWidthSmall();
        addObject(wallWidthSmall9,335,298);
        wallWidthSmall9.setLocation(334,299);
        WallWidthMedium wallWidthMedium2 = new WallWidthMedium();
        addObject(wallWidthMedium2,123,245);
        wallWidthMedium2.setLocation(151,238);
        wallWidthMedium2.setLocation(150,240);
        WallWidthMedium wallWidthMedium3 = new WallWidthMedium();
        addObject(wallWidthMedium3,179,181);
        wallWidthMedium3.setLocation(223,184);
        WallWidthSmall wallWidthSmall10 = new WallWidthSmall();
        addObject(wallWidthSmall10,319,181);
        wallWidthSmall10.setLocation(332,184);
        WallWidthMedium wallWidthMedium4 = new WallWidthMedium();
        addObject(wallWidthMedium4,327,122);
        wallWidthMedium4.setLocation(373,123);
        WallWidthSmall wallWidthSmall11 = new WallWidthSmall();
        addObject(wallWidthSmall11,449,116);
        wallWidthSmall11.setLocation(482,123);
        wallWidthMedium4.setLocation(357,120);
        wallWidthMedium4.setLocation(371,123);
        WallWidthMedium wallWidthMedium5 = new WallWidthMedium();
        addObject(wallWidthMedium5,437,53);
        wallWidthMedium5.setLocation(447,64);
        WallWidthSmall wallWidthSmall12 = new WallWidthSmall();
        addObject(wallWidthSmall12,533,57);
        wallWidthSmall12.setLocation(556,65);
        wallWidthSmall12.setLocation(578,66);
        wallWidthSmall12.setLocation(568,64);
        wallWidthSmall12.setLocation(565,64);
        wallWidthSmall12.setLocation(557,61);
        wallWidthSmall12.setLocation(557,64);
        WallWidthMedium wallWidthMedium6 = new WallWidthMedium();
        addObject(wallWidthMedium6,592,292);
        wallWidthMedium6.setLocation(600,299);
        WallWidthSmall wallWidthSmall13 = new WallWidthSmall();
        addObject(wallWidthSmall13,495,305);
        wallWidthSmall13.setLocation(491,296);
        wallWidthSmall13.setLocation(487,298);
        WallHeightSmall wallHeightSmall12 = new WallHeightSmall();
        addObject(wallHeightSmall12,452,339);
        wallHeightSmall12.setLocation(448,333);
        WallWidthSmall wallWidthSmall14 = new WallWidthSmall();
        addObject(wallWidthSmall14,396,355);
        wallWidthSmall14.setLocation(411,359);
        WallWidthMedium wallWidthMedium7 = new WallWidthMedium();
        addObject(wallWidthMedium7,676,412);
        wallWidthMedium7.setLocation(673,421);
        WallWidthMedium wallWidthMedium8 = new WallWidthMedium();
        addObject(wallWidthMedium8,91,419);
        wallWidthMedium8.setLocation(75,418);
        WallWidthSmall wallWidthSmall15 = new WallWidthSmall();
        addObject(wallWidthSmall15,39,538);
        wallWidthSmall15.setLocation(35,538);
        WallWidthMedium wallWidthMedium9 = new WallWidthMedium();
        addObject(wallWidthMedium9,100,478);
        wallWidthMedium9.setLocation(147,481);
        WallWidthMedium wallWidthMedium10 = new WallWidthMedium();
        addObject(wallWidthMedium10,273,478);
        wallWidthMedium10.setLocation(296,481);
        wallWidthMedium10.setLocation(356,479);
        wallWidthMedium10.setLocation(299,483);
        wallWidthMedium10.setLocation(297,481);
        WallWidthMedium wallWidthMedium11 = new WallWidthMedium();
        addObject(wallWidthMedium11,571,540);
        wallWidthMedium11.setLocation(596,538);
        WallWidthSmall wallWidthSmall16 = new WallWidthSmall();
        addObject(wallWidthSmall16,692,536);
        wallWidthSmall16.setLocation(703,538);
        WallWidthMedium wallWidthMedium12 = new WallWidthMedium();
        addObject(wallWidthMedium12,49,117);
        wallWidthMedium12.setLocation(76,120);
        WallWidthMedium wallWidthMedium13 = new WallWidthMedium();
        addObject(wallWidthMedium13,113,362);
        wallWidthMedium13.setLocation(147,360);
        WallWidthSmall wallWidthSmall17 = new WallWidthSmall();
        addObject(wallWidthSmall17,237,357);
        wallWidthSmall17.setLocation(259,361);
        wallWidthSmall17.setLocation(260,360);
        WallHeightLong wallHeightLong = new WallHeightLong();
        addObject(wallHeightLong,715,183);
        wallHeightLong.setLocation(754,138);
        wallHeightLong.setLocation(749,116);
        WallHeightLong wallHeightLong2 = new WallHeightLong();
        addObject(wallHeightLong2,646,342);
        wallHeightLong2.setLocation(745,453);
        wallHeightLong2.setLocation(749,507);
        WallHeightSmall wallHeightSmall13 = new WallHeightSmall();
        addObject(wallHeightSmall13,689,239);
        wallHeightSmall13.setLocation(749,277);
        WallHeightMedium wallHeightMedium = new WallHeightMedium();
        addObject(wallHeightMedium,69,181);
        wallHeightMedium.setLocation(74,186);
        WallHeightMedium wallHeightMedium2 = new WallHeightMedium();
        addObject(wallHeightMedium2,219,96);
        wallHeightMedium2.setLocation(225,66);
        WallHeightSmall wallHeightSmall14 = new WallHeightSmall();
        addObject(wallHeightSmall14,229,155);
        wallHeightSmall14.setLocation(224,154);
        wallHeightSmall14.setLocation(225,139);
        wallHeightSmall14.setLocation(223,148);
        wallHeightSmall14.setLocation(227,155);
        wallHeightSmall14.setLocation(225,155);
        WallHeightMedium wallHeightMedium3 = new WallHeightMedium();
        addObject(wallHeightMedium3,586,55);
        wallHeightMedium3.setLocation(597,68);
        wallWidthSmall12.setLocation(599,70);
        WallHeightSmall wallHeightSmall15 = new WallHeightSmall();
        addObject(wallHeightSmall15,606,152);
        wallHeightSmall15.setLocation(599,157);
        WallHeightMedium wallHeightMedium4 = new WallHeightMedium();
        addObject(wallHeightMedium4,616,395);
        wallHeightMedium4.setLocation(599,418);
        WallHeightMedium wallHeightMedium5 = new WallHeightMedium();
        addObject(wallHeightMedium5,527,465);
        wallHeightMedium5.setLocation(448,534);
        WallHeightMedium wallHeightMedium6 = new WallHeightMedium();
        addObject(wallHeightMedium6,527,497);
        wallHeightMedium6.setLocation(524,485);
        WallHeightMedium wallHeightMedium7 = new WallHeightMedium();
        addObject(wallHeightMedium7,373,488);
        wallHeightMedium7.setLocation(375,482);
        wallHeightMedium7.setLocation(374,483);
        WallHeightSmall wallHeightSmall16 = new WallHeightSmall();
        addObject(wallHeightSmall16,369,394);
        wallHeightSmall16.setLocation(374,394);
        WallHeightMedium wallHeightMedium8 = new WallHeightMedium();
        addObject(wallHeightMedium8,509,337);
        wallHeightMedium8.setLocation(523,181);
        WallHeightSmall wallHeightSmall17 = new WallHeightSmall();
        addObject(wallHeightSmall17,526,261);
        wallHeightSmall17.setLocation(524,266);
        WallHeightSmall wallHeightSmall18 = new WallHeightSmall();
        addObject(wallHeightSmall18,529,317);
        wallHeightSmall18.setLocation(523,333);
        WallHeightMedium wallHeightMedium9 = new WallHeightMedium();
        addObject(wallHeightMedium9,654,145);
        wallHeightMedium9.setLocation(672,120);
        WallHeightMedium wallHeightMedium10 = new WallHeightMedium();
        addObject(wallHeightMedium10,667,200);
        wallHeightMedium10.setLocation(668,242);
        wallHeightMedium10.setLocation(674,205);
        wallHeightMedium10.setLocation(674,205);
        wallHeightMedium9.setLocation(670,116);
        wallHeightMedium9.setLocation(674,116);
        WallHeightMedium wallHeightMedium11 = new WallHeightMedium();
        addObject(wallHeightMedium11,674,307);
        wallHeightMedium11.setLocation(674,307);
        WallHeightLong wallHeightLong3 = new WallHeightLong();
        addObject(wallHeightLong3,21,198);
        wallHeightLong3.setLocation(3,155);
        WallHeightLong wallHeightLong4 = new WallHeightLong();
        addObject(wallHeightLong4,54,342);
        wallHeightLong4.setLocation(2,394);
        wallWidthSmall12.setLocation(529,65);
        wallWidthMedium5.setLocation(540,67);
        wallWidthSmall12.setLocation(550,64);
        wallWidthMedium5.setLocation(380,64);
        wallWidthMedium5.setLocation(439,64);
        Mouse mouse = new Mouse();
        addObject(mouse,39,554);
        mouse.setLocation(32,566);
        removeObject(wallWidthSmall14);
        WallHeightSmall wallHeightSmall19 = new WallHeightSmall();
        addObject(wallHeightSmall19,673,396);
        wallHeightSmall19.setLocation(674,393);
        Cheese cheese = new Cheese();
        addObject(cheese,40,85);
        Cheese cheese2 = new Cheese();
        addObject(cheese2,559,35);
        Cheese cheese3 = new Cheese();
        addObject(cheese3,710,563);
        Cheese cheese4 = new Cheese();
        addObject(cheese4,637,382);
        Cheese cheese5 = new Cheese();
        addObject(cheese5,39,157);
        Teleporter teleporter = new Teleporter();
        addObject(teleporter,35,330);
        Teleporter teleporter2 = new Teleporter();
        addObject(teleporter2,107,95);
        Teleporter teleporter3 = new Teleporter();
        addObject(teleporter3,646,448);
    }
}
